# Generated by Django 3.2.8 on 2021-12-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='age',
        ),
    ]
