# Generated by Django 3.2.8 on 2021-12-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0002_remove_patientrecord_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
