# Generated by Django 3.2.6 on 2021-10-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0003_doctor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
