# Generated by Django 3.2.6 on 2021-12-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0003_alter_doctor_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='null_boolean_field',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
