# Generated by Django 3.2.8 on 2021-10-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0005_alter_doctor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
