# Generated by Django 3.2.8 on 2021-10-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0006_alter_doctor_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='prefix',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('MD', 'MD'), ('RN', 'RN')], max_length=2),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='type',
            field=models.CharField(choices=[('D', 'Doctor'), ('N', 'Nurse'), ('S', 'Secretary')], max_length=2),
        ),
    ]
