# Generated by Django 3.2.8 on 2021-10-15 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccinerecordapp', '0007_auto_20211016_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('suffix', models.CharField(max_length=100, null=True)),
                ('nick_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('bday', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField(null=True)),
                ('mobile', models.CharField(max_length=11, null=True)),
                ('landline', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('home_no', models.CharField(max_length=100)),
                ('brgy', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('zip_code', models.CharField(max_length=4, null=True)),
                ('lname_mom', models.CharField(max_length=100)),
                ('fname_mom', models.CharField(max_length=100)),
                ('contact_mom', models.CharField(max_length=100)),
                ('email_mom', models.EmailField(max_length=100)),
                ('lname_dad', models.CharField(max_length=100)),
                ('fname_dad', models.CharField(max_length=100)),
                ('contact_dad', models.CharField(max_length=100)),
                ('email_dad', models.EmailField(max_length=100)),
                ('lname_e1', models.CharField(max_length=100)),
                ('fname_e1', models.CharField(max_length=100)),
                ('relation_e1', models.CharField(max_length=100)),
                ('contact_e1', models.CharField(max_length=100)),
                ('name_e2', models.CharField(max_length=100)),
                ('fname_e2', models.CharField(max_length=100)),
                ('relation_e2', models.CharField(max_length=100)),
                ('contact_e2', models.CharField(max_length=100)),
                ('doctor_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccinerecordapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
