# Generated by Django 3.2.8 on 2021-10-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0009_auto_20211016_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6, null=True),
        ),
    ]
