# Generated by Django 3.2.6 on 2021-10-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0012_auto_20211017_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='doctor_assigned',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
