# Generated by Django 3.2.6 on 2021-10-17 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccinerecordapp', '0013_alter_patientrecord_doctor_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='doctor_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccinerecordapp.doctor'),
        ),
    ]
