# Generated by Django 3.2.6 on 2021-10-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0014_auto_20211017_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
