# Generated by Django 3.2.8 on 2021-10-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0015_patientrecord_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='username',
        ),
    ]
