# Generated by Django 3.2.8 on 2021-10-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0016_remove_patientrecord_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='name_e2',
            new_name='lname_e2',
        ),
    ]
