# Generated by Django 3.2.8 on 2021-10-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0017_rename_name_e2_patientrecord_lname_e2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='bday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='brgy',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='contact_dad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='contact_e1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='contact_e2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='contact_mom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='email_dad',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='email_mom',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='fname_dad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='fname_e1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='fname_e2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='fname_mom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='home_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='landline',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='lname_dad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='lname_e1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='lname_e2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='lname_mom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='province',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='region',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='relation_e1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='relation_e2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='zip_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
