# Generated by Django 3.2.8 on 2021-11-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0021_rename_vaccinerecord_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='anf_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='bcg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dtap1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dtap2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dtap3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dtap4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dtap5_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hepa1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hepa2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hepb1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hepb2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hepb3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hib1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hib2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hib3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hib4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hpv11_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hpv12_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hpv21_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hpv22_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='hpv23_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='inf1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='inf2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='ipv1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='ipv2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='ipv3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='ipv4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='ipv5_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='japb1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='japb2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='men_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='mmr1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='mmr2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='msl_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='pcv1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='pcv2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='pcv3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='pcv4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='rota1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='rota2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='rota3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='td_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='typ_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='var1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='var2_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
