# Generated by Django 3.2.8 on 2021-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0023_auto_20211101_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='user',
            field=models.IntegerField(max_length=1000, null=True),
        ),
    ]
