# Generated by Django 3.2.8 on 2021-11-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0025_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
