# Generated by Django 3.2.8 on 2021-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0026_auto_20211101_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='patient_no',
            field=models.IntegerField(null=True),
        ),
    ]
