# Generated by Django 3.2.8 on 2021-11-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0026_appointment_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='verified',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('UC', 'Unconfirmed'), ('P', 'Postponed')], default='UC', max_length=2),
        ),
    ]
