# Generated by Django 3.2.8 on 2021-11-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0027_vaccine_patient_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='patient_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
