# Generated by Django 3.2.8 on 2021-11-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0028_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('UC', 'Unconfirmed'), ('P', 'Postponed')], max_length=10),
        ),
    ]
