# Generated by Django 3.2.8 on 2021-11-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0030_remove_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('UC', 'Confirmed')], default='UC', max_length=2),
        ),
    ]
