# Generated by Django 3.2.8 on 2021-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0031_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(choices=[('MD', 'MD'), ('RN', 'RN')], default='MD', max_length=2),
            preserve_default=False,
        ),
    ]
