# Generated by Django 3.2.8 on 2021-11-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0032_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(choices=[('C', 'Confirmed'), ('UC', 'Confirmed'), ('P', 'Postponed')], max_length=2),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('C', 'Confirmed'), ('UC', 'Confirmed'), ('P', 'Postponed')], max_length=2),
        ),
    ]
