# Generated by Django 3.2.8 on 2021-11-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0035_auto_20211101_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='status',
            new_name='title',
        ),
    ]
