# Generated by Django 3.2.8 on 2021-11-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0036_rename_status_appointment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='title',
            new_name='status',
        ),
    ]
