# Generated by Django 3.2.8 on 2021-11-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0037_rename_title_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='status',
            new_name='stat',
        ),
    ]
