# Generated by Django 3.2.8 on 2021-11-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0039_alter_appointment_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='stat',
            field=models.CharField(choices=[('C', 'Confirmed'), ('UC', 'Unconfirmed'), ('P', 'Postponed')], max_length=2),
        ),
    ]
