# Generated by Django 3.2.8 on 2021-11-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0042_remove_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='stats',
            field=models.CharField(choices=[('C', 'Confirmed'), ('UC', 'Unconfirmed'), ('P', 'Postponed')], default='UC', max_length=2),
            preserve_default=False,
        ),
    ]
