# Generated by Django 3.2.8 on 2021-11-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0043_appointment_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='stats',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='stat',
            field=models.CharField(choices=[('C', 'Confirmed'), ('UC', 'Unconfirmed'), ('P', 'Postponed')], default='UC', max_length=2),
        ),
    ]
