# Generated by Django 3.2.8 on 2021-11-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0028_alter_vaccine_patient_no'),
        ('vaccinerecordapp', '0046_vaccine'),
    ]

    operations = [
    ]
