# Generated by Django 3.2.6 on 2021-11-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinerecordapp', '0048_alter_appointment_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(blank=True, choices=[('MD', 'MD'), ('RN', 'RN')], max_length=2),
        ),
    ]
